### ISSUE TITLE
This shows up as Pastiche and it doesn't work.

### ISSUE THREAD

**Issue by rolltidehero** [mattneary/command-t#1]
Instead, it opens a sidebar to add snippets???

![image](https://user-images.githubusercontent.com/11590510/148148867-d65105e0-9b82-4c4f-ae76-c4749881d5c0.png)

**Comment by mattneary** [comment]
Thanks for flagging this. I must've overridden this extension with another side project at some point 🤦‍♂️

I've submitted a fix for review by Google, but I'll have to wait and see when they'll approve the update.

**Comment by mattneary** [comment]
Closing because the update is now available in the Chrome store. Please reach out with any additional issues.
